# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43b1c81b5d83ab26035583bbae183732ef6ff440bab6d8419dfe7984c728654ea3ed2a25ca19109e5386230e343f4261a3a22f5dac754dfcc21dbab849bf426b

test:
  secret_key_base: 50b4485633843473725715bed2d99f8c362e1cb53a623f74f7ab74c8edb6a31494f43fa547e4345c4ea3acfe0ff87e7b61aa137c448ea7a355e3f63470c64dc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
